# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "tests"
  tests:

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # A strategy creates a build matrix for your jobs
    strategy:

      # You can define a matrix of different job configurations
      matrix:

        # Each option you define in the matrix has a key and value
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [ 3.9 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Setup Python with version from matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install requirements
      - name: Install requirements

        shell: bash
        # Runs command-line programs using the operating system's shell
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip list

          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install antlr4
          elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install antlr4
          else
              brew install antlr
          fi

      # Generate GQL ANTLR
      - name: Generate GQL ANTLR

        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              cd project/gql/parser/grammar
              antlr4 -Dlanguage=Python3 -visitor ./gql.g4 -o ../antlr
          elif [ "$RUNNER_OS" == "Windows" ]; then
              cd project/gql/parser/grammar
              antlr4 -Dlanguage=Python3 -visitor ./gql.g4 -o ../antlr
          else
              cd project/gql/parser/grammar
              antlr4 -Dlanguage=Python3 -visitor ./gql.g4 -o ../antlr
          fi

      # Run unit tests using pytest
      - name: Run unit tests
        run: |
          pytest -vv ./tests
